// Flat ESLint config. eslint-config-next 16 ships native flat-config arrays,
// so the old FlatCompat/@eslint/eslintrc bridge is no longer needed.
//
// Pinned to ESLint 9.x: eslint-config-next 16.3.1 bundles eslint-plugin-react 7.x,
// which still calls the `context.getFilename()` API that ESLint 10 removed.
// Revisit once eslint-plugin-react ships an ESLint 10 compatible release.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const eslintConfig = [
    {
        ignores: [
            ".next/**",
            "out/**",
            "public/worklets/**", // generated by scripts/build-worklet.js
            "public/audio-engine-wasm/**", // generated by wasm-pack
            "core-audio/wasm/target/**", // cargo build artifacts
        ],
    },
    ...nextCoreWebVitals,
    ...nextTypeScript,
    {
        rules: {
            // `_`-prefixed args/vars are an intentional "unused on purpose" marker
            // used throughout the worklet and hooks.
            "@typescript-eslint/no-unused-vars": [
                "warn",
                {
                    argsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                    caughtErrorsIgnorePattern: "^_",
                },
            ],
            // eslint-plugin-react-hooks 7 added the React Compiler rule set. It surfaces
            // real render-correctness/perf issues in existing components, tracked in
            // docs/AUDIO-AUDIT.md ("UI / React render layer"). Kept at `warn` so the
            // findings stay visible while they are worked through; flip back to `error`
            // once the backlog is clear.
            "react-hooks/refs": "warn",
            "react-hooks/set-state-in-effect": "warn",
            "react-hooks/immutability": "warn",
        },
    },
    {
        // The AudioWorklet bundle has no module imports by design — it runs in the
        // worklet isolate and picks up ambient types via triple-slash references.
        files: ["core-audio/worklet/**/*.ts"],
        rules: {
            "@typescript-eslint/triple-slash-reference": "off",
        },
    },
];

export default eslintConfig;
