#!/bin/bash

# Build the Rust/WASM audio engine
echo "Building Rust/WASM audio engine..."
cd core-audio/wasm
wasm-pack build --target web

echo "Injecting @generated warning headers into created WASM JS..."
sed -i '' '1s/^/\/\* @generated \n * This file is automatically generated by wasm-bindgen. DO NOT EDIT.\n * Any changes made here will be overwritten on the next build.\n \*\/\n/' pkg/audio_engine.js

# Copy the generated files to the Next.js src directory (for main-thread imports)
echo "Copying WASM files to Next.js src directory..."
cd ../..
mkdir -p src/core-audio/wasm-wasm
cp -r core-audio/wasm/pkg/. src/core-audio/wasm-wasm/

# Also copy to public for AudioWorklet to import by URL
echo "Copying WASM files to public directory for AudioWorklet..."
mkdir -p public/audio-engine-wasm
cp -r core-audio/wasm/pkg/. public/audio-engine-wasm/

echo "✅ WASM build complete!"
