#!/usr/bin/env bash
#
# build-wasm.sh — compile the Rust DSP crate to WASM and publish it to public/.
#
# The AudioWorklet loads the engine at runtime by fetching
# `public/audio-engine-wasm/{audio_engine.js,audio_engine_bg.wasm}` and evaluating
# the wasm-bindgen glue inside the worklet isolate (see core-audio/client/audioManager.ts).
# Nothing imports the WASM through the bundler, so public/ is the only output that matters.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRATE_DIR="$ROOT/core-audio/wasm"
OUT_DIR="$ROOT/public/audio-engine-wasm"

if ! command -v wasm-pack >/dev/null 2>&1; then
    echo "error: wasm-pack not found. Install it with:" >&2
    echo "  cargo install wasm-pack   # or: https://rustwasm.github.io/wasm-pack/installer/" >&2
    exit 1
fi

if ! rustup target list --installed 2>/dev/null | grep -qx "wasm32-unknown-unknown"; then
    echo "Adding the wasm32-unknown-unknown target..."
    rustup target add wasm32-unknown-unknown
fi

echo "Building Rust/WASM audio engine..."
cd "$CRATE_DIR"

# wasm-opt gives a meaningful size/perf win, but wasm-pack downloads binaryen on first
# use — which fails in sandboxed or offline environments (e.g. CI without egress). Fall
# back to an unoptimised build rather than failing the whole build.
if ! wasm-pack build --target web; then
    echo "warning: wasm-pack build failed (usually the binaryen/wasm-opt download)." >&2
    echo "         Retrying with --no-opt; the output will be larger and slightly slower." >&2
    wasm-pack build --target web --no-opt
fi

echo "Injecting @generated warning header into the wasm-bindgen JS..."
GLUE="$CRATE_DIR/pkg/audio_engine.js"
HEADER='/* @generated
 * This file is automatically generated by wasm-bindgen. DO NOT EDIT.
 * Any changes made here will be overwritten on the next build.
 */'
if ! head -n 1 "$GLUE" | grep -q "@generated"; then
    printf '%s\n%s' "$HEADER" "$(cat "$GLUE")" > "$GLUE.tmp"
    mv "$GLUE.tmp" "$GLUE"
fi

echo "Publishing to public/audio-engine-wasm for the AudioWorklet to fetch..."
mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/audio_engine*.js "$OUT_DIR"/audio_engine*.wasm "$OUT_DIR"/audio_engine*.d.ts
cp "$CRATE_DIR"/pkg/audio_engine.js \
   "$CRATE_DIR"/pkg/audio_engine.d.ts \
   "$CRATE_DIR"/pkg/audio_engine_bg.wasm \
   "$CRATE_DIR"/pkg/audio_engine_bg.wasm.d.ts \
   "$CRATE_DIR"/pkg/package.json \
   "$OUT_DIR/"

echo "✅ WASM build complete → $OUT_DIR"
